FROM rocker/r-devel

RUN apt update && \
  apt install -y libgdal-dev && \
  apt install -y pandoc

RUN Rscript -e 'install.packages(c("RCurl", "rjson", "maps", "gtools", "terra", "curl", "roxygen2", "testthat"))'
