FROM rocker/r-devel

RUN apt-get update && \
  apt-get install -y libgdal-dev && \
  apt-get install -y pandoc

RUN Rscript -e 'install.packages(c("RCurl", "rjson", "maps", "gtools", "terra", "curl", "roxygen2", "testthat"))'
