FROM rocker/r-devel

RUN apt-get update && \
  apt-get install -y libgdal-dev pandoc tidy

RUN Rscript -e 'install.packages(c("curl", "rjson", "maps", "gtools", "terra", "curl", "roxygen2", "testthat"))'
